[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm install --omit=dev"]

[phases.build]
cmds = ["echo 'No build step needed for server'"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production" 