name: Deploy Clean Master Platform

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Test client build
      run: |
        cd client
        npm install
        npm run build
    
    - name: Test server
      run: |
        cd server
        npm install
        npm test || echo "No tests configured"

  deploy-info:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Deployment Ready
      run: |
        echo "✅ Tests passed! Ready for deployment"
        echo "🚀 Deploy manually to:"
        echo "   - Server: Railway (railway.app)"
        echo "   - Client: Vercel (vercel.com)"
        echo "📚 See DEPLOYMENT_GUIDE.md for instructions" 